extend type Exercise {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Exercise", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Exercise`.`workout`. It must match the value of `Workout`.`id`. See `@ref` for how to customize it.
  """
  workoutId: UUID! @fdc_generated(from: "Exercise.workout", purpose: IMPLICIT_REF_FIELD)
}
extend type ExerciseSet {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ExerciseSet", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `ExerciseSet`.`exercise`. It must match the value of `Exercise`.`id`. See `@ref` for how to customize it.
  """
  exerciseId: UUID! @fdc_generated(from: "ExerciseSet.exercise", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
extend type Workout {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Workout", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Workout`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Workout.user", purpose: IMPLICIT_REF_FIELD)
}
