type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Workout @table {
  user: User!
  name: String!
  date: Date!
  completed: Boolean!
  createdAt: Timestamp!
  updatedAt: Timestamp!
}

type Exercise @table {
  workout: Workout!
  name: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  youtubeLink: String
}

type ExerciseSet @table {
  exercise: Exercise!
  reps: Int!
  measurement: String!
  completed: Boolean!
  createdAt: Timestamp!
  updatedAt: Timestamp!
}
